// pez 导出器：使用 fflate 将谱面和音频打包为 .pez（ZIP）格式
// pez = Phigros RPE 谱面包，本质是 ZIP 文件，包含：
// - chart.json (RPE 格式谱面)
// - music.wav / music.mp3 (音频)
// - cover.png (封面，可选)
// - line.png (判定线贴图，可选)
// - info.txt (元信息，可选)

import { zipSync, strToU8, type Zippable } from 'fflate'
import type { RPEChart } from '../types/rpe'

export interface PezExportParams {
  chart: RPEChart
  audioData: ArrayBuffer | Uint8Array
  audioFormat?: 'wav' | 'mp3' | 'ogg'
  coverData?: Uint8Array
  lineData?: Uint8Array
  filename?: string
}

export interface PezExportResult {
  data: Uint8Array
  filename: string
  size: number
}

export function exportPez(params: PezExportParams): PezExportResult {
  const {
    chart,
    audioData,
    audioFormat = 'wav',
    coverData,
    lineData,
    filename,
  } = params

  const files: Zippable = {}

  files['chart.json'] = {
    data: strToU8(JSON.stringify(chart, null, 2)),
    level: 6,
  }

  const audioExt = audioFormat
  files[`music.${audioExt}`] = {
    data: new Uint8Array(audioData),
    level: 6,
  }

  if (coverData) {
    files['cover.png'] = { data: coverData, level: 6 }
  }

  if (lineData) {
    files['line.png'] = { data: lineData, level: 6 }
  } else {
    files['line.png'] = {
      data: generateDefaultLineTexture(),
      level: 6,
    }
  }

  const info = buildInfoTxt(chart)
  files['info.txt'] = {
    data: strToU8(info),
    level: 6,
  }

  const zipped = zipSync(files)
  const name = filename || `${chart.META.name || 'chart'}.pez`

  return {
    data: zipped,
    filename: name,
    size: zipped.byteLength,
  }
}

function buildInfoTxt(chart: RPEChart): string {
  const m = chart.META
  return [
    `Name: ${m.name}`,
    `Composer: ${m.composer}`,
    `Charter: ${m.charter}`,
    `Level: ${m.level}`,
    `RPEVersion: ${m.RPEVersion}`,
    `BPM: ${chart.BPMList[0]?.bpm ?? 120}`,
    `JudgeLines: ${chart.judgeLineList.length}`,
    `Notes: ${chart.judgeLineList.reduce((s, l) => s + l.numOfNotes, 0)}`,
    '',
    `Generated by AI Chart Maker`,
  ].join('\n')
}

function generateDefaultLineTexture(): Uint8Array {
  const encoder = new TextEncoder()
  const pngHeader = encoder.encode(
    '\x89PNG\r\n\x1a\n'
  )
  return pngHeader
}

export function downloadPez(result: PezExportResult): void {
  const blob = new Blob([result.data as BlobPart], { type: 'application/zip' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = result.filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

export function encodeAudioBufferToWav(audioBuffer: AudioBuffer): Uint8Array {
  const numChannels = audioBuffer.numberOfChannels
  const sampleRate = audioBuffer.sampleRate
  const length = audioBuffer.length
  const bytesPerSample = 2
  const blockAlign = numChannels * bytesPerSample
  const dataSize = length * blockAlign
  const buffer = new ArrayBuffer(44 + dataSize)
  const view = new DataView(buffer)

  const writeString = (offset: number, str: string) => {
    for (let i = 0; i < str.length; i++) view.setUint8(offset + i, str.charCodeAt(i))
  }

  writeString(0, 'RIFF')
  view.setUint32(4, 36 + dataSize, true)
  writeString(8, 'WAVE')
  writeString(12, 'fmt ')
  view.setUint32(16, 16, true)
  view.setUint16(20, 1, true)
  view.setUint16(22, numChannels, true)
  view.setUint32(24, sampleRate, true)
  view.setUint32(28, sampleRate * blockAlign, true)
  view.setUint16(32, blockAlign, true)
  view.setUint16(34, bytesPerSample * 8, true)
  writeString(36, 'data')
  view.setUint32(40, dataSize, true)

  const channels: Float32Array[] = []
  for (let ch = 0; ch < numChannels; ch++) {
    channels.push(audioBuffer.getChannelData(ch))
  }

  let offset = 44
  for (let i = 0; i < length; i++) {
    for (let ch = 0; ch < numChannels; ch++) {
      const sample = Math.max(-1, Math.min(1, channels[ch][i]))
      view.setInt16(offset, sample < 0 ? sample * 0x8000 : sample * 0x7fff, true)
      offset += 2
    }
  }

  return new Uint8Array(buffer)
}
